// <auto-generated />
using System;
using GKVK_Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GKVK_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250617123134_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GKVK_Api.Models.Domain.OrgUnit", b =>
                {
                    b.Property<int>("OrgUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgUnitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateSourceId")
                        .HasColumnType("int");

                    b.HasKey("OrgUnitId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TemplateSourceId");

                    b.ToTable("OrgUnits");

                    b.HasData(
                        new
                        {
                            OrgUnitId = 1000,
                            Name = "KVK Template"
                        },
                        new
                        {
                            OrgUnitId = 2000,
                            Name = "Farmers Training Institute (FTI)"
                        },
                        new
                        {
                            OrgUnitId = 3000,
                            Name = "Staff Training Unit (STU)"
                        },
                        new
                        {
                            OrgUnitId = 3001,
                            Name = "SAMETI – DESI Programme",
                            ParentId = 3000
                        },
                        new
                        {
                            OrgUnitId = 4000,
                            Name = "Farm Information Unit (FIU)"
                        },
                        new
                        {
                            OrgUnitId = 5000,
                            Name = "Institute of Baking Technology & Value Addition (IBT&VA)"
                        },
                        new
                        {
                            OrgUnitId = 6000,
                            Name = "Agricultural Technology Information Centre (ATIC)"
                        },
                        new
                        {
                            OrgUnitId = 7000,
                            Name = "Distance Education Unit (DEU)"
                        },
                        new
                        {
                            OrgUnitId = 8000,
                            Name = "Agricultural Sciences Museum (ASM)"
                        },
                        new
                        {
                            OrgUnitId = 9000,
                            Name = "National Agriculture Extension Project (NAEP)"
                        },
                        new
                        {
                            OrgUnitId = 9500,
                            Name = "Extension Education Unit (EEU)"
                        });
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FK_UserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("FK_UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TableColumn", b =>
                {
                    b.Property<int>("TableColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableColumnId"));

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("TableDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("TableColumnId");

                    b.HasIndex("TableDefinitionId");

                    b.ToTable("TableColumns");

                    b.HasData(
                        new
                        {
                            TableColumnId = 110101,
                            DataType = 0,
                            Name = "Title",
                            Position = 1,
                            TableDefinitionId = 1101
                        },
                        new
                        {
                            TableColumnId = 110102,
                            DataType = 0,
                            Name = "Crop",
                            Position = 2,
                            TableDefinitionId = 1101
                        },
                        new
                        {
                            TableColumnId = 110103,
                            DataType = 5,
                            Name = "Area(ha)",
                            Position = 3,
                            TableDefinitionId = 1101
                        },
                        new
                        {
                            TableColumnId = 110104,
                            DataType = 1,
                            Name = "NoOfTrials_Male_SC/ST",
                            Position = 4,
                            TableDefinitionId = 1101
                        },
                        new
                        {
                            TableColumnId = 110105,
                            DataType = 1,
                            Name = "NoOfTrials_Male_Gen",
                            Position = 5,
                            TableDefinitionId = 1101
                        },
                        new
                        {
                            TableColumnId = 110106,
                            DataType = 1,
                            Name = "NoOfTrials_Female_SC/ST",
                            Position = 6,
                            TableDefinitionId = 1101
                        },
                        new
                        {
                            TableColumnId = 110107,
                            DataType = 1,
                            Name = "NoOfTrials_Female_Gen",
                            Position = 7,
                            TableDefinitionId = 1101
                        },
                        new
                        {
                            TableColumnId = 110108,
                            DataType = 5,
                            Name = "Yield(q/ha)_Y1",
                            Position = 8,
                            TableDefinitionId = 1101
                        },
                        new
                        {
                            TableColumnId = 110109,
                            DataType = 5,
                            Name = "Yield(q/ha)_Y2",
                            Position = 9,
                            TableDefinitionId = 1101
                        },
                        new
                        {
                            TableColumnId = 110110,
                            DataType = 5,
                            Name = "%IncreaseOverT2",
                            Position = 10,
                            TableDefinitionId = 1101
                        },
                        new
                        {
                            TableColumnId = 110201,
                            DataType = 0,
                            Name = "Title",
                            Position = 1,
                            TableDefinitionId = 1102
                        },
                        new
                        {
                            TableColumnId = 110202,
                            DataType = 0,
                            Name = "Crop",
                            Position = 2,
                            TableDefinitionId = 1102
                        },
                        new
                        {
                            TableColumnId = 110203,
                            DataType = 5,
                            Name = "Area(ha)",
                            Position = 3,
                            TableDefinitionId = 1102
                        },
                        new
                        {
                            TableColumnId = 110204,
                            DataType = 1,
                            Name = "NoOfTrials_Male_SC/ST",
                            Position = 4,
                            TableDefinitionId = 1102
                        },
                        new
                        {
                            TableColumnId = 110205,
                            DataType = 1,
                            Name = "NoOfTrials_Male_Gen",
                            Position = 5,
                            TableDefinitionId = 1102
                        },
                        new
                        {
                            TableColumnId = 110206,
                            DataType = 1,
                            Name = "NoOfTrials_Female_SC/ST",
                            Position = 6,
                            TableDefinitionId = 1102
                        },
                        new
                        {
                            TableColumnId = 110207,
                            DataType = 1,
                            Name = "NoOfTrials_Female_Gen",
                            Position = 7,
                            TableDefinitionId = 1102
                        },
                        new
                        {
                            TableColumnId = 110208,
                            DataType = 5,
                            Name = "Yield(q/ha)_Y1",
                            Position = 8,
                            TableDefinitionId = 1102
                        },
                        new
                        {
                            TableColumnId = 110209,
                            DataType = 5,
                            Name = "Yield(q/ha)_Y2",
                            Position = 9,
                            TableDefinitionId = 1102
                        },
                        new
                        {
                            TableColumnId = 110210,
                            DataType = 5,
                            Name = "%IncreaseOverT2",
                            Position = 10,
                            TableDefinitionId = 1102
                        },
                        new
                        {
                            TableColumnId = 110301,
                            DataType = 3,
                            Name = "Date",
                            Position = 1,
                            TableDefinitionId = 1103
                        },
                        new
                        {
                            TableColumnId = 110302,
                            DataType = 0,
                            Name = "Title",
                            Position = 2,
                            TableDefinitionId = 1103
                        },
                        new
                        {
                            TableColumnId = 110303,
                            DataType = 0,
                            Name = "Thematic area*",
                            Position = 3,
                            TableDefinitionId = 1103
                        },
                        new
                        {
                            TableColumnId = 110304,
                            DataType = 0,
                            Name = "Type**",
                            Position = 4,
                            TableDefinitionId = 1103
                        },
                        new
                        {
                            TableColumnId = 110305,
                            DataType = 1,
                            Name = "NoOfTrials_Male_SC/ST",
                            Position = 5,
                            TableDefinitionId = 1103
                        },
                        new
                        {
                            TableColumnId = 110306,
                            DataType = 1,
                            Name = "NoOfTrials_Male_Gen",
                            Position = 6,
                            TableDefinitionId = 1103
                        },
                        new
                        {
                            TableColumnId = 110307,
                            DataType = 1,
                            Name = "NoOfTrials_Female_SC/ST",
                            Position = 7,
                            TableDefinitionId = 1103
                        },
                        new
                        {
                            TableColumnId = 110308,
                            DataType = 1,
                            Name = "NoOfTrials_Female_Gen",
                            Position = 8,
                            TableDefinitionId = 1103
                        },
                        new
                        {
                            TableColumnId = 110401,
                            DataType = 3,
                            Name = "Date",
                            Position = 1,
                            TableDefinitionId = 1104
                        },
                        new
                        {
                            TableColumnId = 110402,
                            DataType = 0,
                            Name = "Title",
                            Position = 2,
                            TableDefinitionId = 1104
                        },
                        new
                        {
                            TableColumnId = 110403,
                            DataType = 0,
                            Name = "Thematic area*",
                            Position = 3,
                            TableDefinitionId = 1104
                        },
                        new
                        {
                            TableColumnId = 110404,
                            DataType = 0,
                            Name = "Type**",
                            Position = 4,
                            TableDefinitionId = 1104
                        },
                        new
                        {
                            TableColumnId = 110405,
                            DataType = 0,
                            Name = "Village/Taluk",
                            Position = 5,
                            TableDefinitionId = 1104
                        },
                        new
                        {
                            TableColumnId = 110406,
                            DataType = 1,
                            Name = "NoOfTrials_Male_SC/ST",
                            Position = 6,
                            TableDefinitionId = 1104
                        },
                        new
                        {
                            TableColumnId = 110407,
                            DataType = 1,
                            Name = "NoOfTrials_Male_Gen",
                            Position = 7,
                            TableDefinitionId = 1104
                        },
                        new
                        {
                            TableColumnId = 110408,
                            DataType = 1,
                            Name = "NoOfTrials_Female_SC/ST",
                            Position = 8,
                            TableDefinitionId = 1104
                        },
                        new
                        {
                            TableColumnId = 110409,
                            DataType = 1,
                            Name = "NoOfTrials_Female_Gen",
                            Position = 9,
                            TableDefinitionId = 1104
                        },
                        new
                        {
                            TableColumnId = 132101,
                            DataType = 1,
                            Name = "SlNo",
                            Position = 1,
                            TableDefinitionId = 1321
                        },
                        new
                        {
                            TableColumnId = 132102,
                            DataType = 0,
                            Name = "Message",
                            Position = 2,
                            TableDefinitionId = 1321
                        },
                        new
                        {
                            TableColumnId = 132103,
                            DataType = 0,
                            Name = "Category",
                            Position = 3,
                            TableDefinitionId = 1321
                        },
                        new
                        {
                            TableColumnId = 132201,
                            DataType = 3,
                            Name = "Date",
                            Position = 1,
                            TableDefinitionId = 1322
                        },
                        new
                        {
                            TableColumnId = 132202,
                            DataType = 0,
                            Name = "ParticipatingCenter",
                            Position = 2,
                            TableDefinitionId = 1322
                        },
                        new
                        {
                            TableColumnId = 132203,
                            DataType = 0,
                            Name = "Purpose",
                            Position = 3,
                            TableDefinitionId = 1322
                        },
                        new
                        {
                            TableColumnId = 132301,
                            DataType = 0,
                            Name = "Details",
                            Position = 1,
                            TableDefinitionId = 1323
                        },
                        new
                        {
                            TableColumnId = 140001,
                            DataType = 0,
                            Name = "Story",
                            Position = 1,
                            TableDefinitionId = 1400
                        },
                        new
                        {
                            TableColumnId = 210101,
                            DataType = 1,
                            Name = "SlNo",
                            Position = 1,
                            TableDefinitionId = 2101
                        },
                        new
                        {
                            TableColumnId = 210102,
                            DataType = 0,
                            Name = "SponsoredOrganization",
                            Position = 2,
                            TableDefinitionId = 2101
                        },
                        new
                        {
                            TableColumnId = 210103,
                            DataType = 0,
                            Name = "TrainingTitle",
                            Position = 3,
                            TableDefinitionId = 2101
                        },
                        new
                        {
                            TableColumnId = 210104,
                            DataType = 3,
                            Name = "Date",
                            Position = 4,
                            TableDefinitionId = 2101
                        },
                        new
                        {
                            TableColumnId = 210105,
                            DataType = 0,
                            Name = "Duration",
                            Position = 5,
                            TableDefinitionId = 2101
                        },
                        new
                        {
                            TableColumnId = 210106,
                            DataType = 1,
                            Name = "NoOfTrainings",
                            Position = 6,
                            TableDefinitionId = 2101
                        },
                        new
                        {
                            TableColumnId = 210107,
                            DataType = 1,
                            Name = "NoOfParticipants",
                            Position = 7,
                            TableDefinitionId = 2101
                        },
                        new
                        {
                            TableColumnId = 210201,
                            DataType = 0,
                            Name = "Details",
                            Position = 1,
                            TableDefinitionId = 2102
                        },
                        new
                        {
                            TableColumnId = 310101,
                            DataType = 1,
                            Name = "SlNo",
                            Position = 1,
                            TableDefinitionId = 3101
                        },
                        new
                        {
                            TableColumnId = 310102,
                            DataType = 0,
                            Name = "TrainingTitle",
                            Position = 2,
                            TableDefinitionId = 3101
                        },
                        new
                        {
                            TableColumnId = 310103,
                            DataType = 0,
                            Name = "DateAndPlace",
                            Position = 3,
                            TableDefinitionId = 3101
                        },
                        new
                        {
                            TableColumnId = 310104,
                            DataType = 0,
                            Name = "Duration",
                            Position = 4,
                            TableDefinitionId = 3101
                        },
                        new
                        {
                            TableColumnId = 310105,
                            DataType = 1,
                            Name = "NoOfTrainings",
                            Position = 5,
                            TableDefinitionId = 3101
                        },
                        new
                        {
                            TableColumnId = 310106,
                            DataType = 1,
                            Name = "NoOfParticipants",
                            Position = 6,
                            TableDefinitionId = 3101
                        },
                        new
                        {
                            TableColumnId = 310201,
                            DataType = 1,
                            Name = "SlNo",
                            Position = 1,
                            TableDefinitionId = 3102
                        },
                        new
                        {
                            TableColumnId = 310202,
                            DataType = 0,
                            Name = "SponsoredOrganization",
                            Position = 2,
                            TableDefinitionId = 3102
                        },
                        new
                        {
                            TableColumnId = 310203,
                            DataType = 0,
                            Name = "TrainingTitle",
                            Position = 3,
                            TableDefinitionId = 3102
                        },
                        new
                        {
                            TableColumnId = 310204,
                            DataType = 0,
                            Name = "DateAndPlace",
                            Position = 4,
                            TableDefinitionId = 3102
                        },
                        new
                        {
                            TableColumnId = 310205,
                            DataType = 0,
                            Name = "Duration",
                            Position = 5,
                            TableDefinitionId = 3102
                        },
                        new
                        {
                            TableColumnId = 310206,
                            DataType = 1,
                            Name = "NoOfTrainings",
                            Position = 6,
                            TableDefinitionId = 3102
                        },
                        new
                        {
                            TableColumnId = 310207,
                            DataType = 1,
                            Name = "NoOfParticipants",
                            Position = 7,
                            TableDefinitionId = 3102
                        },
                        new
                        {
                            TableColumnId = 310301,
                            DataType = 0,
                            Name = "Details",
                            Position = 1,
                            TableDefinitionId = 3103
                        },
                        new
                        {
                            TableColumnId = 320101,
                            DataType = 1,
                            Name = "SlNo",
                            Position = 1,
                            TableDefinitionId = 3201
                        },
                        new
                        {
                            TableColumnId = 320102,
                            DataType = 0,
                            Name = "Place",
                            Position = 2,
                            TableDefinitionId = 3201
                        },
                        new
                        {
                            TableColumnId = 320103,
                            DataType = 0,
                            Name = "NodalTrainingInstitute",
                            Position = 3,
                            TableDefinitionId = 3201
                        },
                        new
                        {
                            TableColumnId = 320104,
                            DataType = 1,
                            Name = "NoOfBatch",
                            Position = 4,
                            TableDefinitionId = 3201
                        },
                        new
                        {
                            TableColumnId = 320105,
                            DataType = 1,
                            Name = "NoOfInputDealers",
                            Position = 5,
                            TableDefinitionId = 3201
                        },
                        new
                        {
                            TableColumnId = 320201,
                            DataType = 0,
                            Name = "Details",
                            Position = 1,
                            TableDefinitionId = 3202
                        },
                        new
                        {
                            TableColumnId = 410101,
                            DataType = 1,
                            Name = "SlNo",
                            Position = 1,
                            TableDefinitionId = 4101
                        },
                        new
                        {
                            TableColumnId = 410102,
                            DataType = 0,
                            Name = "ActivityType",
                            Position = 2,
                            TableDefinitionId = 4101
                        },
                        new
                        {
                            TableColumnId = 410103,
                            DataType = 1,
                            Name = "Number",
                            Position = 3,
                            TableDefinitionId = 4101
                        },
                        new
                        {
                            TableColumnId = 510101,
                            DataType = 1,
                            Name = "SlNo",
                            Position = 1,
                            TableDefinitionId = 5101
                        },
                        new
                        {
                            TableColumnId = 510102,
                            DataType = 0,
                            Name = "TrainingDetails",
                            Position = 2,
                            TableDefinitionId = 5101
                        },
                        new
                        {
                            TableColumnId = 510103,
                            DataType = 1,
                            Name = "Number",
                            Position = 3,
                            TableDefinitionId = 5101
                        },
                        new
                        {
                            TableColumnId = 510104,
                            DataType = 1,
                            Name = "NoOfProgramme",
                            Position = 4,
                            TableDefinitionId = 5101
                        },
                        new
                        {
                            TableColumnId = 510105,
                            DataType = 0,
                            Name = "DateAndPlace",
                            Position = 5,
                            TableDefinitionId = 5101
                        },
                        new
                        {
                            TableColumnId = 510106,
                            DataType = 0,
                            Name = "Duration",
                            Position = 6,
                            TableDefinitionId = 5101
                        },
                        new
                        {
                            TableColumnId = 510107,
                            DataType = 1,
                            Name = "NoOfParticipants",
                            Position = 7,
                            TableDefinitionId = 5101
                        },
                        new
                        {
                            TableColumnId = 510201,
                            DataType = 0,
                            Name = "Details",
                            Position = 1,
                            TableDefinitionId = 5102
                        },
                        new
                        {
                            TableColumnId = 610101,
                            DataType = 1,
                            Name = "SlNo",
                            Position = 1,
                            TableDefinitionId = 6101
                        },
                        new
                        {
                            TableColumnId = 610102,
                            DataType = 0,
                            Name = "ServiceType",
                            Position = 2,
                            TableDefinitionId = 6101
                        },
                        new
                        {
                            TableColumnId = 610103,
                            DataType = 1,
                            Name = "Nos",
                            Position = 3,
                            TableDefinitionId = 6101
                        },
                        new
                        {
                            TableColumnId = 610104,
                            DataType = 1,
                            Name = "NoOfBeneficiaries",
                            Position = 4,
                            TableDefinitionId = 6101
                        },
                        new
                        {
                            TableColumnId = 610201,
                            DataType = 1,
                            Name = "SlNo",
                            Position = 1,
                            TableDefinitionId = 6102
                        },
                        new
                        {
                            TableColumnId = 610202,
                            DataType = 0,
                            Name = "InputDetails",
                            Position = 2,
                            TableDefinitionId = 6102
                        },
                        new
                        {
                            TableColumnId = 610203,
                            DataType = 0,
                            Name = "Quantity",
                            Position = 3,
                            TableDefinitionId = 6102
                        },
                        new
                        {
                            TableColumnId = 610204,
                            DataType = 2,
                            Name = "Amount",
                            Position = 4,
                            TableDefinitionId = 6102
                        },
                        new
                        {
                            TableColumnId = 610301,
                            DataType = 0,
                            Name = "Details",
                            Position = 1,
                            TableDefinitionId = 6103
                        },
                        new
                        {
                            TableColumnId = 710101,
                            DataType = 0,
                            Name = "CourseName",
                            Position = 1,
                            TableDefinitionId = 7101
                        },
                        new
                        {
                            TableColumnId = 710102,
                            DataType = 1,
                            Name = "CandidatesAdmitted",
                            Position = 2,
                            TableDefinitionId = 7101
                        },
                        new
                        {
                            TableColumnId = 710103,
                            DataType = 1,
                            Name = "AttendedExam",
                            Position = 3,
                            TableDefinitionId = 7101
                        },
                        new
                        {
                            TableColumnId = 710104,
                            DataType = 1,
                            Name = "Passed",
                            Position = 4,
                            TableDefinitionId = 7101
                        },
                        new
                        {
                            TableColumnId = 710201,
                            DataType = 0,
                            Name = "CourseName",
                            Position = 1,
                            TableDefinitionId = 7102
                        },
                        new
                        {
                            TableColumnId = 710202,
                            DataType = 1,
                            Name = "CandidatesAdmitted",
                            Position = 2,
                            TableDefinitionId = 7102
                        },
                        new
                        {
                            TableColumnId = 710203,
                            DataType = 1,
                            Name = "AttendedExam",
                            Position = 3,
                            TableDefinitionId = 7102
                        },
                        new
                        {
                            TableColumnId = 710204,
                            DataType = 1,
                            Name = "Passed",
                            Position = 4,
                            TableDefinitionId = 7102
                        },
                        new
                        {
                            TableColumnId = 710301,
                            DataType = 0,
                            Name = "Details",
                            Position = 1,
                            TableDefinitionId = 7103
                        },
                        new
                        {
                            TableColumnId = 810101,
                            DataType = 0,
                            Name = "InstitutionName",
                            Position = 1,
                            TableDefinitionId = 8101
                        },
                        new
                        {
                            TableColumnId = 810102,
                            DataType = 3,
                            Name = "DateOfVisit",
                            Position = 2,
                            TableDefinitionId = 8101
                        },
                        new
                        {
                            TableColumnId = 810103,
                            DataType = 1,
                            Name = "NoOfVisitors",
                            Position = 3,
                            TableDefinitionId = 8101
                        },
                        new
                        {
                            TableColumnId = 910101,
                            DataType = 0,
                            Name = "Particulars",
                            Position = 1,
                            TableDefinitionId = 9101
                        },
                        new
                        {
                            TableColumnId = 910102,
                            DataType = 3,
                            Name = "Date",
                            Position = 2,
                            TableDefinitionId = 9101
                        },
                        new
                        {
                            TableColumnId = 910103,
                            DataType = 0,
                            Name = "Place",
                            Position = 3,
                            TableDefinitionId = 9101
                        },
                        new
                        {
                            TableColumnId = 910104,
                            DataType = 1,
                            Name = "NoOfProgrammes",
                            Position = 4,
                            TableDefinitionId = 9101
                        },
                        new
                        {
                            TableColumnId = 910105,
                            DataType = 1,
                            Name = "NoOfParticipants",
                            Position = 5,
                            TableDefinitionId = 9101
                        },
                        new
                        {
                            TableColumnId = 951101,
                            DataType = 0,
                            Name = "Title",
                            Position = 1,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951102,
                            DataType = 0,
                            Name = "Crop",
                            Position = 2,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951103,
                            DataType = 0,
                            Name = "Area",
                            Position = 3,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951104,
                            DataType = 1,
                            Name = "Trials_SC_Male",
                            Position = 4,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951105,
                            DataType = 1,
                            Name = "Trials_SC_Female",
                            Position = 5,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951106,
                            DataType = 1,
                            Name = "Trials_ST_Male",
                            Position = 6,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951107,
                            DataType = 1,
                            Name = "Trials_ST_Female",
                            Position = 7,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951108,
                            DataType = 1,
                            Name = "Trials_General_Male",
                            Position = 8,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951109,
                            DataType = 1,
                            Name = "Trials_General_Female",
                            Position = 9,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951110,
                            DataType = 2,
                            Name = "Yield_T1",
                            Position = 10,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951111,
                            DataType = 2,
                            Name = "Yield_T2",
                            Position = 11,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951112,
                            DataType = 2,
                            Name = "%IncreaseOverT2",
                            Position = 12,
                            TableDefinitionId = 9511
                        },
                        new
                        {
                            TableColumnId = 951201,
                            DataType = 0,
                            Name = "Title",
                            Position = 1,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951202,
                            DataType = 0,
                            Name = "Crop",
                            Position = 2,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951203,
                            DataType = 0,
                            Name = "Area",
                            Position = 3,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951204,
                            DataType = 1,
                            Name = "Trials_SC_Male",
                            Position = 4,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951205,
                            DataType = 1,
                            Name = "Trials_SC_Female",
                            Position = 5,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951206,
                            DataType = 1,
                            Name = "Trials_ST_Male",
                            Position = 6,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951207,
                            DataType = 1,
                            Name = "Trials_ST_Female",
                            Position = 7,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951208,
                            DataType = 1,
                            Name = "Trials_General_Male",
                            Position = 8,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951209,
                            DataType = 1,
                            Name = "Trials_General_Female",
                            Position = 9,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951210,
                            DataType = 2,
                            Name = "Yield_Demo",
                            Position = 10,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951211,
                            DataType = 2,
                            Name = "Yield_Check",
                            Position = 11,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951212,
                            DataType = 2,
                            Name = "%IncreaseOverCheck",
                            Position = 12,
                            TableDefinitionId = 9512
                        },
                        new
                        {
                            TableColumnId = 951301,
                            DataType = 1,
                            Name = "SlNo",
                            Position = 1,
                            TableDefinitionId = 9513
                        },
                        new
                        {
                            TableColumnId = 951302,
                            DataType = 0,
                            Name = "Title",
                            Position = 2,
                            TableDefinitionId = 9513
                        },
                        new
                        {
                            TableColumnId = 951303,
                            DataType = 3,
                            Name = "Date",
                            Position = 3,
                            TableDefinitionId = 9513
                        },
                        new
                        {
                            TableColumnId = 951304,
                            DataType = 0,
                            Name = "Duration",
                            Position = 4,
                            TableDefinitionId = 9513
                        },
                        new
                        {
                            TableColumnId = 951305,
                            DataType = 1,
                            Name = "NoOfProgrammes",
                            Position = 5,
                            TableDefinitionId = 9513
                        },
                        new
                        {
                            TableColumnId = 951306,
                            DataType = 1,
                            Name = "NoOfParticipants",
                            Position = 6,
                            TableDefinitionId = 9513
                        });
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TableDataCell", b =>
                {
                    b.Property<int>("TableDataCellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableDataCellId"));

                    b.Property<int>("TableColumnId")
                        .HasColumnType("int");

                    b.Property<int>("TableDataRowId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TableDataCellId");

                    b.HasIndex("TableColumnId");

                    b.HasIndex("TableDataRowId");

                    b.ToTable("TableDataCells");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TableDataRow", b =>
                {
                    b.Property<int>("TableDataRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableDataRowId"));

                    b.Property<int>("OrgUnitId")
                        .HasColumnType("int");

                    b.Property<int>("TableDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TableDataRowId");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("TableDefinitionId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TableDataRows");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TableDefinition", b =>
                {
                    b.Property<int>("TableDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableDefinitionId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("OrgUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TableDefinitionId");

                    b.HasIndex("OrgUnitId");

                    b.ToTable("TableDefinitions");

                    b.HasData(
                        new
                        {
                            TableDefinitionId = 1101,
                            DisplayOrder = 1,
                            OrgUnitId = 1000,
                            Title = "1. OFT"
                        },
                        new
                        {
                            TableDefinitionId = 1102,
                            DisplayOrder = 2,
                            OrgUnitId = 1000,
                            Title = "2. FLD"
                        },
                        new
                        {
                            TableDefinitionId = 1103,
                            DisplayOrder = 3,
                            OrgUnitId = 1000,
                            Title = "3. On-Campus Training Programs Conducted"
                        },
                        new
                        {
                            TableDefinitionId = 1104,
                            DisplayOrder = 4,
                            OrgUnitId = 1000,
                            Title = "4. Off-Campus Training Programs Conducted"
                        },
                        new
                        {
                            TableDefinitionId = 1321,
                            DisplayOrder = 321,
                            OrgUnitId = 1000,
                            Title = "32.1 Short Messages"
                        },
                        new
                        {
                            TableDefinitionId = 1322,
                            DisplayOrder = 322,
                            OrgUnitId = 1000,
                            Title = "32.2 Expert Center"
                        },
                        new
                        {
                            TableDefinitionId = 1323,
                            DisplayOrder = 323,
                            OrgUnitId = 1000,
                            Title = "32.3 Other E‑KVK Activities"
                        },
                        new
                        {
                            TableDefinitionId = 1400,
                            DisplayOrder = 400,
                            OrgUnitId = 1000,
                            Title = "40. Any Other Story"
                        },
                        new
                        {
                            TableDefinitionId = 2101,
                            DisplayOrder = 1,
                            OrgUnitId = 2000,
                            Title = "Training Programmes Organized"
                        },
                        new
                        {
                            TableDefinitionId = 2102,
                            DisplayOrder = 2,
                            OrgUnitId = 2000,
                            Title = "Any Other Activities"
                        },
                        new
                        {
                            TableDefinitionId = 3101,
                            DisplayOrder = 1,
                            OrgUnitId = 3000,
                            Title = "Training Programmes Organized"
                        },
                        new
                        {
                            TableDefinitionId = 3102,
                            DisplayOrder = 2,
                            OrgUnitId = 3000,
                            Title = "Sponsored Training Programmes Organized"
                        },
                        new
                        {
                            TableDefinitionId = 3103,
                            DisplayOrder = 3,
                            OrgUnitId = 3000,
                            Title = "Any Other Activities"
                        },
                        new
                        {
                            TableDefinitionId = 3201,
                            DisplayOrder = 1,
                            OrgUnitId = 3001,
                            Title = "DESI Programme"
                        },
                        new
                        {
                            TableDefinitionId = 3202,
                            DisplayOrder = 2,
                            OrgUnitId = 3001,
                            Title = "Any Other Activities"
                        },
                        new
                        {
                            TableDefinitionId = 4101,
                            DisplayOrder = 1,
                            OrgUnitId = 4000,
                            Title = "Activities / Programmes"
                        },
                        new
                        {
                            TableDefinitionId = 5101,
                            DisplayOrder = 1,
                            OrgUnitId = 5000,
                            Title = "Programmes Organized"
                        },
                        new
                        {
                            TableDefinitionId = 5102,
                            DisplayOrder = 2,
                            OrgUnitId = 5000,
                            Title = "Any Other Activities"
                        },
                        new
                        {
                            TableDefinitionId = 6101,
                            DisplayOrder = 1,
                            OrgUnitId = 6000,
                            Title = "Advisory Services"
                        },
                        new
                        {
                            TableDefinitionId = 6102,
                            DisplayOrder = 2,
                            OrgUnitId = 6000,
                            Title = "Sale of Inputs / Plant Materials"
                        },
                        new
                        {
                            TableDefinitionId = 6103,
                            DisplayOrder = 3,
                            OrgUnitId = 6000,
                            Title = "Any Other Activities"
                        },
                        new
                        {
                            TableDefinitionId = 7101,
                            DisplayOrder = 1,
                            OrgUnitId = 7000,
                            Title = "Diploma Courses"
                        },
                        new
                        {
                            TableDefinitionId = 7102,
                            DisplayOrder = 2,
                            OrgUnitId = 7000,
                            Title = "Certificate Courses"
                        },
                        new
                        {
                            TableDefinitionId = 7103,
                            DisplayOrder = 3,
                            OrgUnitId = 7000,
                            Title = "Any Other Activities"
                        },
                        new
                        {
                            TableDefinitionId = 8101,
                            DisplayOrder = 1,
                            OrgUnitId = 8000,
                            Title = "Museum Visits"
                        },
                        new
                        {
                            TableDefinitionId = 9101,
                            DisplayOrder = 1,
                            OrgUnitId = 9000,
                            Title = "Extension Programmes"
                        },
                        new
                        {
                            TableDefinitionId = 9511,
                            DisplayOrder = 1,
                            OrgUnitId = 9500,
                            Title = "OFT (On‑Farm Trials)"
                        },
                        new
                        {
                            TableDefinitionId = 9512,
                            DisplayOrder = 2,
                            OrgUnitId = 9500,
                            Title = "FLD (Frontline Demonstrations)"
                        },
                        new
                        {
                            TableDefinitionId = 9513,
                            DisplayOrder = 3,
                            OrgUnitId = 9500,
                            Title = "Training Programmes Organized"
                        });
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TrainerUnitAssignment", b =>
                {
                    b.Property<int>("TrainerUnitAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerUnitAssignmentId"));

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrgUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UnassignedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TrainerUnitAssignmentId");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("UserId", "OrgUnitId", "UnassignedOn")
                        .HasDatabaseName("IX_Assignment_Active");

                    b.ToTable("TrainerUnitAssignments");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.OrgUnit", b =>
                {
                    b.HasOne("GKVK_Api.Models.Domain.OrgUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GKVK_Api.Models.Domain.OrgUnit", "TemplateSource")
                        .WithMany()
                        .HasForeignKey("TemplateSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");

                    b.Navigation("TemplateSource");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.RefreshToken", b =>
                {
                    b.HasOne("GKVK_Api.Models.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("FK_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TableColumn", b =>
                {
                    b.HasOne("GKVK_Api.Models.Domain.TableDefinition", "TableDefinition")
                        .WithMany("Columns")
                        .HasForeignKey("TableDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableDefinition");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TableDataCell", b =>
                {
                    b.HasOne("GKVK_Api.Models.Domain.TableColumn", "TableColumn")
                        .WithMany()
                        .HasForeignKey("TableColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GKVK_Api.Models.Domain.TableDataRow", "TableDataRow")
                        .WithMany("Cells")
                        .HasForeignKey("TableDataRowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TableColumn");

                    b.Navigation("TableDataRow");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TableDataRow", b =>
                {
                    b.HasOne("GKVK_Api.Models.Domain.OrgUnit", "OrgUnit")
                        .WithMany("DataRows")
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GKVK_Api.Models.Domain.TableDefinition", "TableDefinition")
                        .WithMany("DataRows")
                        .HasForeignKey("TableDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GKVK_Api.Models.Domain.User", "Trainer")
                        .WithMany("CreatedRows")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrgUnit");

                    b.Navigation("TableDefinition");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TableDefinition", b =>
                {
                    b.HasOne("GKVK_Api.Models.Domain.OrgUnit", "OrgUnit")
                        .WithMany("TableDefinitions")
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrgUnit");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TrainerUnitAssignment", b =>
                {
                    b.HasOne("GKVK_Api.Models.Domain.OrgUnit", "OrgUnit")
                        .WithMany("TrainerUnitAssignments")
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GKVK_Api.Models.Domain.User", "User")
                        .WithMany("TrainerUnitAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrgUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.OrgUnit", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("DataRows");

                    b.Navigation("TableDefinitions");

                    b.Navigation("TrainerUnitAssignments");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TableDataRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.TableDefinition", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("DataRows");
                });

            modelBuilder.Entity("GKVK_Api.Models.Domain.User", b =>
                {
                    b.Navigation("CreatedRows");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TrainerUnitAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
